import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/componentcs/header/Header'
import Footer from '../componentcs/Footer'
import {ContextProvider} from '@/context/Context'
import AuthProvider from '@/componentcs/AuthProvider/AuthProvider'
import SupabaseProvider from '@/providers/supabase'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Posts App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <AuthProvider>
        <ContextProvider>
        <SupabaseProvider>
          <div className='container'>
        <Header/>
        {children}
       <Footer/>
       </div>
       </SupabaseProvider>
       </ContextProvider>
       </AuthProvider>
       
        </body>
    </html>
  )
}
